[project]
name = "plex2jellyfin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plexapi>=4.17.2",
    "progress>=1.6.1",
    "requests>=2.32.5",
]
